Induce target failure while Replica rebuild
openebs/e2e-tests pull request #118
Opened 2020-01-01 15:59 UTC by shashank855

**What this PR does / why we need it**:

- Induce target failure when newly created replica is in sync.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

2020-01-02 06:21 UTC, nsathyaseelan requested changes

2020-01-02 06:21 UTC, nsathyaseelan commented on experiments/functional/cvr-scaleup/test.yml
> +              failed_when: "'deleted' not in target_delete_status.stdout"
@shashank855  instead of failed_when use the until condition to check the older target is removed.

2020-01-02 07:29 UTC, gprasath requested changes

2020-01-02 07:29 UTC, gprasath commented on experiments/functional/cvr-scaleup/test.yml
> +            - name: Getting the taget name
target

2020-01-02 07:29 UTC, gprasath commented on experiments/functional/cvr-scaleup/test.yml
> +            - name: Checking for reconstructing state of newely created cvr
newly

2020-01-02 07:29 UTC, gprasath commented on experiments/functional/cvr-scaleup/test.yml
> +              shell: kubectl get cvr {{ pv.stdout }}-{{ csp_name.stdout_lines[0] }} -n {{ operator_ns }} -o jsonpath='{.status.phase}'
we can't assure that the new cvr will be created on csp with index 0. Let us find the csp name prior and use it @shashank855

2020-01-02 13:08 UTC, nsathyaseelan commented on experiments/functional/cvr-scaleup/test.yml
> +            - name: Verifying seccessful deletion of target
@shashank855  typo in successful

2020-01-02 13:08 UTC, gprasath approved these changes

2020-01-03 06:14 UTC, nsathyaseelan approved these changes
lgtm

2020-01-03 06:14 UTC, merged