feat[litmusbook]: Included a litmus experiment to perform the CSPC poolscaledown
openebs/e2e-tests pull request #173
Opened 2020-02-27 09:25 UTC by nsathyaseelan

Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>

- Implemented a litmusbook to perform the pool scaledown.
- Verify the CSPI are all in `ONLINE` state and  Check the Pool pods are all running
- Select the pool [cspi] want to scale down.
- Obtain the node name of the targeted CSPI for scaledown.
- Removed the CSPI entry from the CSPC 

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

2020-02-27 12:56 UTC, w3aman commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/test.yml
> +        - name: Verify the status od CSPI after scaledown the pool
of *

2020-02-28 10:49 UTC, gprasath requested changes

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/README.md
> +| Day-2-ops |  Scale down the cstor CSPC pool and check if its successfully scaled down | OpenEBS | Any          |
check if it scaled down successfully

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/README.md
> +- blockDevices of the scaled down CSPI should be Unclaimed state.
should be in unclaimed state

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/README.md
> +- Pod corresponding to that scaledown pool and the CSPI shouldn't be available.
CSPI and the pool pod corresponding to scaled down pool should be deleted

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/test_vars.yml
> +pool_type: "{{ lookup('env','POOL_TYPE') }}"
unused and undefined variable

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/test.yml
> +             --no-headers -o custom-columns=:.status.phase
use unique, else even if one cspi is online, the task will pass

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/test.yml
> +         #                                                                                  #
TODO

2020-02-28 10:49 UTC, gprasath commented on experiments/functional/day2_ops/cspc_pool/pool_scaledown/pool_scaledown.yml
> +    - name: Getting the Unclaimed block-device from each node
used block devices by cspi

2020-02-28 11:03 UTC, w3aman approved these changes
/lgtm

2020-02-28 12:39 UTC, gprasath approved these changes

2020-02-28 12:39 UTC, merged