Refactor[YAML] - Converting kubectl command into k8s and k8s_facts module for percona application
openebs/e2e-tests pull request #21
Opened 2019-10-10 09:10 UTC by uditgaurav

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

CHANGES:
Changed the kubectl command used in shell module to k8s,k8s_facts module in the following utils.
/utils/fcm/update_litmus_result_resource.yml
/utils/k8s/pre_create_app_deploy.yml
/utils/k8s/create_ns.yml
/utils/k8s/deploy_single_app.yml
/utils/scm/openebs/check_replica_count.yml
/utils/k8s/fetch_app_pod.yml
/utils/scm/applications/mysql/check_db_connection.yml
/utils/scm/openebs/target_affinity_check.yml
/utils/k8s/deprovision_deployment.yml
/utils/k8s/status_testns.yml

TESTS:
After changing, following test were performed:

i.) In Percona - Provision [deployment]
ii.) In Percona - Deprovision [deployment]
iii.) In Busybox - Provision [statefulset]
iv.) In Busybox - Deprovision [statefulset]

[Test_logs.txt](https://github.com/mayadata-io/litmus/files/3711486/Test_logs.txt)

The logs of all the 4 tests has been uploaded please review in case you need it.

TO DO:

In util - k8s/deprovision_deployment.yml
Task name - Delete the application deployment
is left in shell module as by using k8s module the pvc get struct in terminating state

The util status_app_pod.yml is left in shell module because of this issue - #7

2019-10-10 11:11 UTC, ksatchit commented on utils/k8s/deprovision_deployment.yml
> +      until: "result.resources.0.status.phase == 'Running'"
The previous check would ensure all pods belonging having the specific label in that ns is in running state. Will the replacement work the same way (prompted by the `resources.0.status` reference above)

2019-10-10 11:14 UTC, ksatchit commented on utils/k8s/deprovision_deployment.yml
> +      with_items: "{{  openebs_stg_engine.resources }}"
Why do we have `with_items`against a set_fact? It might just overwrite ?

2019-10-10 11:20 UTC, ksatchit commented on utils/k8s/deprovision_deployment.yml
> +                  - "{{ pvname }}"
How are we passing just pvname as selector? It has to be a key:value form right?

2019-10-16 10:43 UTC, nsathyaseelan requested changes

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/deprovision_deployment.yml
> +          - "{{ app_label }}"
try to pick the pv name from labels using fieldselector

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/deprovision_deployment.yml
> +      until: "{{ po_name | json_query('resources[*].status.phase') | unique | length==1}} and {{po_name | json_query('resources[0].status.phase') == 'Running' }}"
remove the second condition

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/deprovision_deployment.yml
> +      with_items: "{{ pv_name.resources }}"
@uditgaurav  remove the irreverent  tasks

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/deprovision_deployment.yml
> +        name: "{{ pvname }}"
try to pick the storage engine from labels using fieldselector

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/fetch_app_pod.yml
> +  with_items: "{{ pod_name.resources }}"
@uditgaurav  can we use field_selector to get the pod name

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/pre_create_app_deploy.yml
> +        name: "{{ lookup('env','PROVIDER_STORAGE_CLASS') }}"
can we add conditions to check the storage class is present or not?

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/k8s/status_testns.yml
> +  until: "'Active' in npstatus.resources.0.status.phase"
can we use json query filter here

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/scm/openebs/check_replica_count.yml
> +       seconds: 30
use wati_for module

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/scm/openebs/target_affinity_check.yml
>    register: app_node
use check condition to know that we re getting resource or not

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/scm/openebs/target_affinity_check.yml
>    register: app_node
and try to use field_selector here to get the node name.

2019-10-16 10:43 UTC, nsathyaseelan commented on utils/scm/openebs/target_affinity_check.yml
> +    namespace: "{{ app_ns }}"
same as above

2019-10-22 13:24 UTC, gprasath approved these changes

2019-10-22 13:30 UTC, nsathyaseelan approved these changes
/lgtm

2019-10-22 13:58 UTC, ksatchit approved these changes
/lgtm

2019-10-23 05:17 UTC, merged