refactor(backup/restore): Add support for CSI based backup/restore
openebs/e2e-tests pull request #416
Opened 2020-06-25 06:46 UTC by shashank855

Signed-off-by:  <ranjanshashank855@gmail.com>

**What this PR does / why we need it**:

- Add support for CSI based Backup/Restore.

**Following is the log of ansible test container:**

- https://gist.github.com/shashank855/775a15d645c9e0eb306e306317c15101

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

- https://github.com/openebs/e2e-tests/issues/415

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

2020-06-25 06:58 UTC, gprasath commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +        shell: kubectl get csp {{item}} -n {{ operator }} -o jsonpath='{.metadata.name}'
namespace not required

2020-06-25 07:05 UTC, nsathyaseelan requested changes

2020-06-25 07:05 UTC, nsathyaseelan commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +      - name: Getting the CVR name from the corresponding PV
Getting cspi name

2020-06-25 07:05 UTC, nsathyaseelan commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +      - name: Geting the CSPI name corresponding to CVR
In this task also we are getting cspi name only

2020-06-25 07:08 UTC, shashank855 commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +      - name: Geting the CSPI name corresponding to CVR
here we are getting CSPI name only

2020-06-25 07:10 UTC, shashank855 commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +      - name: Getting the CVR name from the corresponding PV
Getting CVR name in this task.

2020-06-25 07:13 UTC, nsathyaseelan commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +      - name: Getting the CVR name from the corresponding PV
No @shashank855  here you are getting cspi name as a list can you verify

2020-06-25 07:46 UTC, shashank855 commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +      - name: Getting the CVR name from the corresponding PV
Thanks @nsathyaseelan  Got It.. Made the changes

2020-06-25 13:50 UTC, nsathyaseelan approved these changes
lgtm

2020-06-25 13:54 UTC, gprasath commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +        register: csp_pod
where this variable is used. if not necessary, remove this task

2020-06-25 13:59 UTC, gprasath commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +        shell:  kubectl get cvr -n {{ operator }} -l openebs.io/persistent-volume={{ vol_name }} -o jsonpath='{range.items[*]}{.metadata.labels.cstorpool\.openebs\.io/name}{"\n"}{end}'
csp will be obtained here, not cvr

2020-06-26 06:46 UTC, shashank855 commented on experiments/functional/backup_and_restore/cstor_post_restore.yml
> +        shell:  kubectl get cvr -n {{ operator }} -l openebs.io/persistent-volume={{ vol_name }} -o jsonpath='{range.items[*]}{.metadata.labels.cstorpool\.openebs\.io/name}{"\n"}{end}'
Made the change.

2020-06-26 06:53 UTC, gprasath approved these changes

2020-06-26 06:54 UTC, merged