feat(exp): adding e2e-test for zfspv shared mount support
openebs/e2e-tests pull request #457
Opened 2020-07-20 08:03 UTC by w3aman

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>

**What this PR does / why we need it**

- This PR adds e2e-test for zfspv shared mount support.
- Applications who wants to share a volume can use below storageclass to make their volumes shared by multiple pods
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
parameters:
  shared: "yes"
  fstype: "zfs"
  poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #436

2020-07-20 10:48 UTC, nsathyaseelan requested changes

2020-07-20 10:48 UTC, nsathyaseelan commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/README.md
> +- For running this litmus experiment of verification of shared mount support for zfspv, update the needed test specific values in run_litmus_test.yml file and create the kubernetes job.
'For running this test case for verification`

2020-07-20 10:48 UTC, nsathyaseelan commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/test.yml
> +            - name: Check the container-status of the new application pod
`container status`

2020-07-20 10:48 UTC, nsathyaseelan commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/test.yml
> +                executable: /bin/bash
can we include any condition to check the labelling is succeed or not?

2020-07-20 10:51 UTC, nsathyaseelan commented
@w3aman  can you provide the test case log

2020-07-21 04:08 UTC, gprasath requested changes

2020-07-21 04:08 UTC, gprasath commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/README.md
> +Note: For run this experiment above storage-class should be present. This storage will be created as a part of zfs-localpv provisioner experiment. If zfs-localpv components are not deployed using e2e
To run/ For running

2020-07-21 04:08 UTC, gprasath commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/README.md
> +4. After that data consistencty is verified from the scaled application pod in the way that data is     accessible from both the pods and after restarting the application pod data should not alter/co
consistency

2020-07-21 04:08 UTC, gprasath commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/README.md
> +4. After that data consistencty is verified from the scaled application pod in the way that data is     accessible from both the pods and after restarting the application pod data should not alter/co
remove tab

2020-07-21 04:08 UTC, gprasath commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/test.yml
> +              until: "replica_count.stdout == '2'"
Don't we wait till it becomes 2

2020-07-21 04:08 UTC, gprasath commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/test.yml
> +                pod_name: "{{ app_pod_name.stdout }}"
can we dump some data from new application pod and verify it in the older one too

2020-07-22 10:31 UTC, nsathyaseelan approved these changes
lgtm

2020-07-27 05:42 UTC, gprasath commented on experiments/functional/zfs-LocalPV/zfspv-shared-mount/README.md
> +4. After that data consistencty is verified from the scaled application pod in the way that data is accessible from both the pods and after restarting the application pod data consistency should be m
consistency

2020-07-27 05:59 UTC, gprasath approved these changes

2020-07-27 05:59 UTC, merged