refact(exp): adding negative test case for provision localpv on selected blockdevice
openebs/e2e-tests pull request #460
Opened 2020-07-22 09:32 UTC by w3aman

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>

**What this PR does / why we need it**:
- This PR adds negative test case for provisioning of localpv on selected device.
- Here for negative testing first we create the storage class where we specify the block device tag
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ sc_name }}
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "device"
      - name: BlockDeviceTag
        value: "{{ device_tag }}"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```
Now we deploy the application but its pvc will remain in pending state. And then we tag the blockdevice with the same label as provided in the storage class. Now pvc should coming in bound state. In this way we can verify the succesful reconcilation of labeling the blockdevice after provisioning the volume.

**Ansible-playbook logs**
1. _positive test case_
[positive_test_case.txt](https://github.com/openebs/e2e-tests/files/4959182/positive_test_case.txt)
2. _negative test case_
[negative_test_case.txt](https://github.com/openebs/e2e-tests/files/4959184/negative_test_case.txt)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #301

2020-07-22 09:38 UTC, nsathyaseelan requested changes
@w3aman can you please modify the readme also

2020-07-23 14:50 UTC, nsathyaseelan approved these changes
lgtm

2020-07-28 07:15 UTC, gprasath requested changes

2020-07-28 07:15 UTC, gprasath commented on experiments/functional/localpv/localpv-provisioning-selected-device/test.yml
> +
can we check the application status here, so that we can check the pvc status after few seconds

2020-07-28 07:15 UTC, gprasath commented on experiments/functional/localpv/localpv-provisioning-selected-device/test.yml
> +          - name: Check if the PVC is in Bound
bound state

2020-07-28 08:44 UTC, gprasath approved these changes

2020-07-28 08:44 UTC, merged