feat(exp): e2e-test for restore the zfs-localpv backup on other nodes
openebs/e2e-tests pull request #555
Opened 2020-10-29 05:21 UTC by w3aman

Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>

**What this PR does / why we need it**:

- This PR adds zfs-localpv restore on different nodes.
- As it is a localpv we use velero restore item action configmap where in configmap we provide the value for, from which node to the other we want to restore.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #553

2020-11-25 05:20 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/restore.yml
> +        when: lookup('env','RESTORE_IN_DIFF_NAMESPACE') == "true"
check the indentation

2020-11-25 06:10 UTC, nsathyaseelan requested changes

2020-11-25 06:10 UTC, nsathyaseelan commented on experiments/zfs-localpv/functional/backup_and_restore/restore.yml
> +   - name: Get the application pod name in app_ns_new namespace
@w3aman Check the task name app_ns_new or {{ app_ns_new }}

2020-12-02 14:50 UTC, w3aman commented
**Restore logs**
```
k8s@k8s-master:~$ kubectl logs -f zfspv-velero-backup-restore-d9pnl-n66mx -n litmus
ansible-playbook 2.7.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/zfs-localpv/functional/backup_and_restore/test.yml
 [WARNING]: Found variable using reserved name: action

PLAY [localhost] ***************************************************************
2020-12-02T14:46:11.122089 (delta: 0.045962)         elapsed: 0.045962 ******** 
=============================================================================== 
META: ran handlers

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:14
2020-12-02T14:46:11.132867 (delta: 0.010752)         elapsed: 0.05674 ********* 
included: /utils/fcm/create_testname.yml for 127.0.0.1

TASK [Record test instance/run ID] *********************************************
task path: /utils/fcm/create_testname.yml:3
2020-12-02T14:46:11.165678 (delta: 0.032795)         elapsed: 0.089551 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Construct testname appended with runID] **********************************
task path: /utils/fcm/create_testname.yml:7
2020-12-02T14:46:11.217371 (delta: 0.051654)         elapsed: 0.141244 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:17
2020-12-02T14:46:11.283230 (delta: 0.065818)         elapsed: 0.207103 ******** 
included: /utils/fcm/update_litmus_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/fcm/update_litmus_result_resource.yml:3
2020-12-02T14:46:11.338085 (delta: 0.054816)         elapsed: 0.261958 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "07906cf469424ec764238d0ecf73e1153f957c5f", "dest": "./litmus-result.yaml", "gid": 0, "group": "root", "md5sum": "23fe89e3cae9ad56bd1be217ff29334d", "mode": "0644", "owner": "root", "size": 428, "src": "/root/.ansible/tmp/ansible-tmp-1606920371.37-53214559640622/source", "state": "file", "uid": 0}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:14
2020-12-02T14:46:11.765687 (delta: 0.427571)         elapsed: 0.68956 ********* 
changed: [127.0.0.1] => {"changed": true, "cmd": "cat litmus-result.yaml", "delta": "0:00:00.562760", "end": "2020-12-02 14:46:12.544362", "rc": 0, "start": "2020-12-02 14:46:11.981602", "stderr": "", "stderr_lines": [], "stdout": "---\napiVersion: litmus.io/v1alpha1\nkind: LitmusResult\nmetadata:\n\n  # name of the litmus testcase\n  name: zfspv-velero-backup-restore \nspec:\n\n  # holds information on the testcase\n  testMetadata:\n    app:  \n    chaostype:  \n\n  # holds the state of testcase,  manually updated by json merge patch\n  # result is the useful value today, but anticipate phase use in future \n  testStatus: \n    phase: in-progress  \n    result: none ", "stdout_lines": ["---", "apiVersion: litmus.io/v1alpha1", "kind: LitmusResult", "metadata:", "", "  # name of the litmus testcase", "  name: zfspv-velero-backup-restore ", "spec:", "", "  # holds information on the testcase", "  testMetadata:", "    app:  ", "    chaostype:  ", "", "  # holds the state of testcase,  manually updated by json merge patch", "  # result is the useful value today, but anticipate phase use in future ", "  testStatus: ", "    phase: in-progress  ", "    result: none "]}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:17
2020-12-02T14:46:12.573852 (delta: 0.808131)         elapsed: 1.497725 ******** 
changed: [127.0.0.1] => {"changed": true, "failed_when_result": false, "method": "patch", "result": {"apiVersion": "litmus.io/v1alpha1", "kind": "LitmusResult", "metadata": {"creationTimestamp": "2020-12-02T14:39:41Z", "generation": 4, "name": "zfspv-velero-backup-restore", "resourceVersion": "372196", "selfLink": "/apis/litmus.io/v1alpha1/litmusresults/zfspv-velero-backup-restore", "uid": "1b5e5969-cf27-42c1-87ae-2f8b5086e703"}, "spec": {"testMetadata": {}, "testStatus": {"phase": "in-progress", "result": "none"}}}}

TASK [Generate the litmus result CR to reflect EOT (End of Test)] **************
task path: /utils/fcm/update_litmus_result_resource.yml:27
2020-12-02T14:46:13.206135 (delta: 0.632164)         elapsed: 2.130008 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:38
2020-12-02T14:46:13.231451 (delta: 0.025282)         elapsed: 2.155324 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:41
2020-12-02T14:46:13.256266 (delta: 0.024769)         elapsed: 2.180139 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Identify the data consistency util to be invoked] ************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:21
2020-12-02T14:46:13.283828 (delta: 0.027533)         elapsed: 2.207701 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "9624e812f35f056e3d1fbe816cdffe51ca61b8d0", "dest": "./data_persistence.yml", "gid": 0, "group": "root", "md5sum": "ad91f65363cc3de694549b37be953585", "mode": "0644", "owner": "root", "size": 81, "src": "/root/.ansible/tmp/ansible-tmp-1606920373.31-129612562141456/source", "state": "file", "uid": 0}

TASK [include_vars] ************************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:26
2020-12-02T14:46:13.570760 (delta: 0.286866)         elapsed: 2.494633 ******** 
ok: [127.0.0.1] => {"ansible_facts": {"consistencyutil": "/utils/scm/applications/busybox/busybox_data_persistence.yml"}, "ansible_included_var_files": ["/experiments/zfs-localpv/functional/backup_and_restore/data_persistence.yml"], "changed": false}

TASK [Record the data consistency util path] ***********************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:29
2020-12-02T14:46:13.614698 (delta: 0.043909)         elapsed: 2.538571 ******** 
ok: [127.0.0.1] => {"ansible_facts": {"data_consistency_util_path": "/utils/scm/applications/busybox/busybox_data_persistence.yml"}, "changed": false}

TASK [Install velero] **********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:34
2020-12-02T14:46:13.671740 (delta: 0.05701)         elapsed: 2.595613 ********* 
included: /experiments/zfs-localpv/functional/backup_and_restore/setup_dependency.yml for 127.0.0.1

TASK [Download velero binary] **************************************************
task path: /experiments/zfs-localpv/functional/ [...]

2020-12-02 14:51 UTC, w3aman commented
**backup logs**

```
k8s@k8s-master:~$ kubectl logs -f zfspv-velero-backup-restore-d4k9x-vhpll -n litmus
ansible-playbook 2.7.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/zfs-localpv/functional/backup_and_restore/test.yml
 [WARNING]: Found variable using reserved name: action

PLAY [localhost] ***************************************************************
2020-12-02T14:41:34.728379 (delta: 0.035693)         elapsed: 0.035693 ******** 
=============================================================================== 
META: ran handlers

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:14
2020-12-02T14:41:34.737117 (delta: 0.008717)         elapsed: 0.044431 ******** 
included: /utils/fcm/create_testname.yml for 127.0.0.1

TASK [Record test instance/run ID] *********************************************
task path: /utils/fcm/create_testname.yml:3
2020-12-02T14:41:34.779118 (delta: 0.041988)         elapsed: 0.086432 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Construct testname appended with runID] **********************************
task path: /utils/fcm/create_testname.yml:7
2020-12-02T14:41:34.859738 (delta: 0.0806)         elapsed: 0.167052 ********** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:17
2020-12-02T14:41:34.895549 (delta: 0.035789)         elapsed: 0.202863 ******** 
included: /utils/fcm/update_litmus_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/fcm/update_litmus_result_resource.yml:3
2020-12-02T14:41:34.941340 (delta: 0.045764)         elapsed: 0.248654 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "07906cf469424ec764238d0ecf73e1153f957c5f", "dest": "./litmus-result.yaml", "gid": 0, "group": "root", "md5sum": "23fe89e3cae9ad56bd1be217ff29334d", "mode": "0644", "owner": "root", "size": 428, "src": "/root/.ansible/tmp/ansible-tmp-1606920094.98-89588413080240/source", "state": "file", "uid": 0}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:14
2020-12-02T14:41:35.431133 (delta: 0.489766)         elapsed: 0.738447 ******** 
changed: [127.0.0.1] => {"changed": true, "cmd": "cat litmus-result.yaml", "delta": "0:00:00.596321", "end": "2020-12-02 14:41:36.264682", "rc": 0, "start": "2020-12-02 14:41:35.668361", "stderr": "", "stderr_lines": [], "stdout": "---\napiVersion: litmus.io/v1alpha1\nkind: LitmusResult\nmetadata:\n\n  # name of the litmus testcase\n  name: zfspv-velero-backup-restore \nspec:\n\n  # holds information on the testcase\n  testMetadata:\n    app:  \n    chaostype:  \n\n  # holds the state of testcase,  manually updated by json merge patch\n  # result is the useful value today, but anticipate phase use in future \n  testStatus: \n    phase: in-progress  \n    result: none ", "stdout_lines": ["---", "apiVersion: litmus.io/v1alpha1", "kind: LitmusResult", "metadata:", "", "  # name of the litmus testcase", "  name: zfspv-velero-backup-restore ", "spec:", "", "  # holds information on the testcase", "  testMetadata:", "    app:  ", "    chaostype:  ", "", "  # holds the state of testcase,  manually updated by json merge patch", "  # result is the useful value today, but anticipate phase use in future ", "  testStatus: ", "    phase: in-progress  ", "    result: none "]}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:17
2020-12-02T14:41:36.303742 (delta: 0.87245)         elapsed: 1.611056 ********* 
changed: [127.0.0.1] => {"changed": true, "failed_when_result": false, "method": "patch", "result": {"apiVersion": "litmus.io/v1alpha1", "kind": "LitmusResult", "metadata": {"creationTimestamp": "2020-12-02T14:39:41Z", "generation": 2, "name": "zfspv-velero-backup-restore", "resourceVersion": "371054", "selfLink": "/apis/litmus.io/v1alpha1/litmusresults/zfspv-velero-backup-restore", "uid": "1b5e5969-cf27-42c1-87ae-2f8b5086e703"}, "spec": {"testMetadata": {}, "testStatus": {"phase": "in-progress", "result": "none"}}}}

TASK [Generate the litmus result CR to reflect EOT (End of Test)] **************
task path: /utils/fcm/update_litmus_result_resource.yml:27
2020-12-02T14:41:36.932467 (delta: 0.628668)         elapsed: 2.239781 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:38
2020-12-02T14:41:36.962793 (delta: 0.030292)         elapsed: 2.270107 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:41
2020-12-02T14:41:36.992184 (delta: 0.029357)         elapsed: 2.299498 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Identify the data consistency util to be invoked] ************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:21
2020-12-02T14:41:37.027732 (delta: 0.035517)         elapsed: 2.335046 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "9624e812f35f056e3d1fbe816cdffe51ca61b8d0", "dest": "./data_persistence.yml", "gid": 0, "group": "root", "md5sum": "ad91f65363cc3de694549b37be953585", "mode": "0644", "owner": "root", "size": 81, "src": "/root/.ansible/tmp/ansible-tmp-1606920097.07-257266730528764/source", "state": "file", "uid": 0}

TASK [include_vars] ************************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:26
2020-12-02T14:41:37.330744 (delta: 0.302914)         elapsed: 2.638058 ******** 
ok: [127.0.0.1] => {"ansible_facts": {"consistencyutil": "/utils/scm/applications/busybox/busybox_data_persistence.yml"}, "ansible_included_var_files": ["/experiments/zfs-localpv/functional/backup_and_restore/data_persistence.yml"], "changed": false}

TASK [Record the data consistency util path] ***********************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:29
2020-12-02T14:41:37.376751 (delta: 0.045974)         elapsed: 2.684065 ******** 
ok: [127.0.0.1] => {"ansible_facts": {"data_consistency_util_path": "/utils/scm/applications/busybox/busybox_data_persistence.yml"}, "changed": false}

TASK [Install velero] **********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:34
2020-12-02T14:41:37.437759 (delta: 0.060973)         elapsed: 2.745073 ******** 
included: /experiments/zfs-localpv/functional/backup_and_restore/setup_dependency.yml for 127.0.0.1

TASK [Download velero binary] **************************************************
task path: /experiments/zfs-localpv/functional/ [...]

2020-12-07 03:14 UTC, nsathyaseelan approved these changes
lgtm

2020-12-07 03:14 UTC, merged