feat(experiment): Included a test case to check the disk replacement is blocked when the block device is already in used by pool
openebs/e2e-tests pull request #556
Opened 2020-10-29 05:47 UTC by nsathyaseelan

Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Checklist**

* [ ] Does this PR have a corresponding GitHub issue?
* [ ] Have you included relevant README for the chaoslib/experiment with details?
* [ ] Have you added debug messages where necessary? 
* [ ] Have you added task comments where necessary? 
* [ ] Have you tested the changes for possible failure conditions?
* [ ] Have you provided the positive & negative test logs for the litmusbook execution?
* [ ] Does the litmusbook ensure idempotency of cluster state?, i.e., is cluster restored to original state?
* [ ] Have you used non-shell/command modules for Kubernetes tasks?
* [ ] Have you (jinja) templatized custom scripts that is run by the litmusbook, if any? 
* [ ] Have you (jinja) templatized Kubernetes deployment manifests used by the litmusbook, if any?
* [ ] Have you reused/created util functions instead of repeating tasks in the litmusbook?
* [ ] Do the artifacts follow the appropriate directory structure? 
* [ ] Have you isolated storage (eg: OpenEBS) specific implementations, checks? 
* [ ] Have you isolated platform (eg: baremetal kubeadm/openshift/aws/gcloud) specific implementations, checks?  
* [ ] Are the ansible facts well defined? Is the scope explicitly set for playbook & included utils?
* [ ] Have you ensured minimum/careful usage of shell utilities (awk, grep, sed, cut, xargs etc.,)?
* [ ] Can the limtusbook be executed both from within & outside a container (configurable paths, no hardcode)?
* [ ] Can you suggest the minimal resource requirements for the litmusbook execution?
* [ ] Does the litmusbook job artifact carry comments/default options/range for the ENV tunables?
* [ ] Has the litmusbooks been linted? 

**Special notes for your reviewer**:

2020-10-29 10:13 UTC, w3aman requested changes

2020-10-29 10:13 UTC, w3aman commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/run_litmus_test.yml
> +        args: ["-c", "ansible-playbook ./experiments/chaos/cspc_pool_failure/disk_replacement_inprogress/test.yml -i /etc/ansible/hosts -v; exit 0"]
file name..
disk_replacement_inprogress ** ??

2020-10-29 10:13 UTC, w3aman commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/run_litmus_test.yml
> +        volumeMounts:
we don't have any `DATA_PERSISTENCE` env....so do we need that?
if not we can remove this configmap...? or add the env

2020-10-29 10:13 UTC, w3aman commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/test.yml
> +        - name: Get cStor Disk Pool names to verify the container statuses
pool pod name **

2020-11-03 08:03 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/README.md
> +Chaos |Verify the BlockDevice replacement is blocked by the adminssion server if the Bd is in claimed state | OpenEBS    | Any          |
Typo

2020-11-03 12:09 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/README.md
> +Chaos |Verify the BlockDevice replacement is blocked by the adminssion server if the Bd is in claimed state | OpenEBS    | Any          |
This is not a chaos

2020-11-03 12:09 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/README.md
> +- This chaos test checks if the cspc pool can be expanded successfully even if the respective pool pod is restarted.
Not chaos

2020-11-03 12:09 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/run_litmus_test.yml
> +  generateName: fail-bd-replacement-when-claimed-bd-
replace 'when' with 'with'

2020-11-03 12:09 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/test.yml
> +        - name: Obtain the pool pod for the targeted node
Obtain the pool pod corresponds to selected cspi

2020-11-03 12:09 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/test.yml
> +          failed_when: 'claimed_bd.stdout == ""'
are we replacing the block device that is already part of same pool?

2020-11-03 12:09 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/test.yml
> +    - /mnt/parameters.yml
this can be removed

2020-11-03 12:13 UTC, gprasath commented on experiments/chaos/cspc_pool_failure/fail_bd_replacement_when_claimed_bd/test.yml
> +
can we check the status of the pool finally

2020-11-04 06:04 UTC, gprasath approved these changes

2020-11-04 06:04 UTC, merged