E2e test for incremental backup and restore for zfs-localpv
openebs/e2e-tests pull request #573
Opened 2020-12-07 15:58 UTC by w3aman

**What this PR does / why we need it**:

- This PR adds e2e test for incremental backup and restore for zfs-localpv.
- Incremental backups works with velero schedule. So first we create schedule and then incremental backups are created.

For more info on Incremental backups for zfspv [click here](https://github.com/openebs/zfs-localpv/blob/master/docs/backup-restore.md)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #551

2020-12-07 15:59 UTC, w3aman commented
**Backup Logs**

```
devuser@rack2:~$ kubectl logs -f zfspv-velero-backup-restore-njv9b-ld8gc -n litmus
ansible-playbook 2.7.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/zfs-localpv/functional/backup_and_restore/test.yml
 [WARNING]: Found variable using reserved name: action

PLAY [localhost] ***************************************************************
2020-12-07T15:43:06.586508 (delta: 0.042225)         elapsed: 0.042225 ******** 
=============================================================================== 
META: ran handlers

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:14
2020-12-07T15:43:06.596494 (delta: 0.009946)         elapsed: 0.052211 ******** 
included: /utils/fcm/create_testname.yml for 127.0.0.1

TASK [Record test instance/run ID] *********************************************
task path: /utils/fcm/create_testname.yml:3
2020-12-07T15:43:06.635209 (delta: 0.038681)         elapsed: 0.090926 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Construct testname appended with runID] **********************************
task path: /utils/fcm/create_testname.yml:7
2020-12-07T15:43:06.740613 (delta: 0.105363)         elapsed: 0.19633 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:17
2020-12-07T15:43:06.776015 (delta: 0.035379)         elapsed: 0.231732 ******** 
included: /utils/fcm/update_litmus_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/fcm/update_litmus_result_resource.yml:3
2020-12-07T15:43:06.822501 (delta: 0.046459)         elapsed: 0.278218 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "07906cf469424ec764238d0ecf73e1153f957c5f", "dest": "./litmus-result.yaml", "gid": 0, "group": "root", "md5sum": "23fe89e3cae9ad56bd1be217ff29334d", "mode": "0644", "owner": "root", "size": 428, "src": "/root/.ansible/tmp/ansible-tmp-1607355786.86-151962762640808/source", "state": "file", "uid": 0}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:14
2020-12-07T15:43:07.258084 (delta: 0.435475)         elapsed: 0.713801 ******** 
changed: [127.0.0.1] => {"changed": true, "cmd": "cat litmus-result.yaml", "delta": "0:00:00.523010", "end": "2020-12-07 15:43:07.995347", "rc": 0, "start": "2020-12-07 15:43:07.472337", "stderr": "", "stderr_lines": [], "stdout": "---\napiVersion: litmus.io/v1alpha1\nkind: LitmusResult\nmetadata:\n\n  # name of the litmus testcase\n  name: zfspv-velero-backup-restore \nspec:\n\n  # holds information on the testcase\n  testMetadata:\n    app:  \n    chaostype:  \n\n  # holds the state of testcase,  manually updated by json merge patch\n  # result is the useful value today, but anticipate phase use in future \n  testStatus: \n    phase: in-progress  \n    result: none ", "stdout_lines": ["---", "apiVersion: litmus.io/v1alpha1", "kind: LitmusResult", "metadata:", "", "  # name of the litmus testcase", "  name: zfspv-velero-backup-restore ", "spec:", "", "  # holds information on the testcase", "  testMetadata:", "    app:  ", "    chaostype:  ", "", "  # holds the state of testcase,  manually updated by json merge patch", "  # result is the useful value today, but anticipate phase use in future ", "  testStatus: ", "    phase: in-progress  ", "    result: none "]}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:17
2020-12-07T15:43:08.022336 (delta: 0.764226)         elapsed: 1.478053 ******** 
changed: [127.0.0.1] => {"changed": true, "failed_when_result": false, "method": "create", "result": {"apiVersion": "litmus.io/v1alpha1", "kind": "LitmusResult", "metadata": {"creationTimestamp": "2020-12-07T15:43:08Z", "generation": 1, "name": "zfspv-velero-backup-restore", "resourceVersion": "358676", "selfLink": "/apis/litmus.io/v1alpha1/litmusresults/zfspv-velero-backup-restore", "uid": "b2dc14b4-245d-4245-bed7-a4a932267d10"}, "spec": {"testMetadata": {"app": null, "chaostype": null}, "testStatus": {"phase": "in-progress", "result": "none"}}}}

TASK [Generate the litmus result CR to reflect EOT (End of Test)] **************
task path: /utils/fcm/update_litmus_result_resource.yml:27
2020-12-07T15:43:08.697373 (delta: 0.674993)         elapsed: 2.15309 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:38
2020-12-07T15:43:08.726276 (delta: 0.02887)         elapsed: 2.181993 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:41
2020-12-07T15:43:08.756153 (delta: 0.029832)         elapsed: 2.21187 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Identify the data consistency util to be invoked] ************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:21
2020-12-07T15:43:08.787158 (delta: 0.030972)         elapsed: 2.242875 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "adc83b19e793491b1c6ea0fd8b46cd9f32e592fc", "dest": "./data_persistence.yml", "gid": 0, "group": "root", "md5sum": "68b329da9893e34099c7d8ad5cb9c940", "mode": "0644", "owner": "root", "size": 1, "src": "/root/.ansible/tmp/ansible-tmp-1607355788.82-22525772080508/source", "state": "file", "uid": 0}

TASK [include_vars] ************************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:26
2020-12-07T15:43:09.085495 (delta: 0.298301)         elapsed: 2.541212 ******** 
ok: [127.0.0.1] => {"ansible_facts": {}, "ansible_included_var_files": ["/experiments/zfs-localpv/functional/backup_and_restore/data_persistence.yml"], "changed": false}

TASK [Record the data consistency util path] ***********************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:29
2020-12-07T15:43:09.132134 (delta: 0.046596)         elapsed: 2.587851 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Install velero] **********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:34
2020-12-07T15:43:09.173900 (delta: 0.041712)         elapsed: 2.629617 ******** 
included: /experiments/zfs-localpv/functional/backup_and_restore/setup_dependency.yml for 127.0.0.1

TASK [Download velero binary] **************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/setup_dependency.yml:1
2020-12-07T15:43:09.251432 (delta: 0.077472)         elapsed: 2.707149 [...]

2020-12-07 16:00 UTC, w3aman commented
**Restore Logs**
```
devuser@rack2:~$ kubectl logs -f  zfspv-velero-backup-restore-d4k9x-vhpll -n litmus
ansible-playbook 2.7.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/zfs-localpv/functional/backup_and_restore/test.yml
 [WARNING]: Found variable using reserved name: action

PLAY [localhost] ***************************************************************
2020-12-07T15:50:22.206056 (delta: 0.036993)         elapsed: 0.036993 ******** 
=============================================================================== 
META: ran handlers

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:14
2020-12-07T15:50:22.214941 (delta: 0.008855)         elapsed: 0.045878 ******** 
included: /utils/fcm/create_testname.yml for 127.0.0.1

TASK [Record test instance/run ID] *********************************************
task path: /utils/fcm/create_testname.yml:3
2020-12-07T15:50:22.245410 (delta: 0.030455)         elapsed: 0.076347 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Construct testname appended with runID] **********************************
task path: /utils/fcm/create_testname.yml:7
2020-12-07T15:50:22.296612 (delta: 0.051169)         elapsed: 0.127549 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] ***********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:17
2020-12-07T15:50:22.348326 (delta: 0.051677)         elapsed: 0.179263 ******** 
included: /utils/fcm/update_litmus_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/fcm/update_litmus_result_resource.yml:3
2020-12-07T15:50:22.392288 (delta: 0.043914)         elapsed: 0.223225 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "07906cf469424ec764238d0ecf73e1153f957c5f", "dest": "./litmus-result.yaml", "gid": 0, "group": "root", "md5sum": "23fe89e3cae9ad56bd1be217ff29334d", "mode": "0644", "owner": "root", "size": 428, "src": "/root/.ansible/tmp/ansible-tmp-1607356222.43-212102770300822/source", "state": "file", "uid": 0}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:14
2020-12-07T15:50:22.875545 (delta: 0.483199)         elapsed: 0.706482 ******** 
changed: [127.0.0.1] => {"changed": true, "cmd": "cat litmus-result.yaml", "delta": "0:00:00.520417", "end": "2020-12-07 15:50:23.664081", "rc": 0, "start": "2020-12-07 15:50:23.143664", "stderr": "", "stderr_lines": [], "stdout": "---\napiVersion: litmus.io/v1alpha1\nkind: LitmusResult\nmetadata:\n\n  # name of the litmus testcase\n  name: zfspv-velero-backup-restore \nspec:\n\n  # holds information on the testcase\n  testMetadata:\n    app:  \n    chaostype:  \n\n  # holds the state of testcase,  manually updated by json merge patch\n  # result is the useful value today, but anticipate phase use in future \n  testStatus: \n    phase: in-progress  \n    result: none ", "stdout_lines": ["---", "apiVersion: litmus.io/v1alpha1", "kind: LitmusResult", "metadata:", "", "  # name of the litmus testcase", "  name: zfspv-velero-backup-restore ", "spec:", "", "  # holds information on the testcase", "  testMetadata:", "    app:  ", "    chaostype:  ", "", "  # holds the state of testcase,  manually updated by json merge patch", "  # result is the useful value today, but anticipate phase use in future ", "  testStatus: ", "    phase: in-progress  ", "    result: none "]}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:17
2020-12-07T15:50:23.695953 (delta: 0.820353)         elapsed: 1.52689 ********* 
changed: [127.0.0.1] => {"changed": true, "failed_when_result": false, "method": "patch", "result": {"apiVersion": "litmus.io/v1alpha1", "kind": "LitmusResult", "metadata": {"creationTimestamp": "2020-12-07T15:43:08Z", "generation": 3, "name": "zfspv-velero-backup-restore", "resourceVersion": "360417", "selfLink": "/apis/litmus.io/v1alpha1/litmusresults/zfspv-velero-backup-restore", "uid": "b2dc14b4-245d-4245-bed7-a4a932267d10"}, "spec": {"testMetadata": {}, "testStatus": {"phase": "in-progress", "result": "none"}}}}

TASK [Generate the litmus result CR to reflect EOT (End of Test)] **************
task path: /utils/fcm/update_litmus_result_resource.yml:27
2020-12-07T15:50:24.399781 (delta: 0.703784)         elapsed: 2.230718 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:38
2020-12-07T15:50:24.430812 (delta: 0.030991)         elapsed: 2.261749 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:41
2020-12-07T15:50:24.461788 (delta: 0.030938)         elapsed: 2.292725 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Identify the data consistency util to be invoked] ************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:21
2020-12-07T15:50:24.493562 (delta: 0.031738)         elapsed: 2.324499 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "adc83b19e793491b1c6ea0fd8b46cd9f32e592fc", "dest": "./data_persistence.yml", "gid": 0, "group": "root", "md5sum": "68b329da9893e34099c7d8ad5cb9c940", "mode": "0644", "owner": "root", "size": 1, "src": "/root/.ansible/tmp/ansible-tmp-1607356224.53-203066244210802/source", "state": "file", "uid": 0}

TASK [include_vars] ************************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:26
2020-12-07T15:50:24.803401 (delta: 0.309803)         elapsed: 2.634338 ******** 
ok: [127.0.0.1] => {"ansible_facts": {}, "ansible_included_var_files": ["/experiments/zfs-localpv/functional/backup_and_restore/data_persistence.yml"], "changed": false}

TASK [Record the data consistency util path] ***********************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:29
2020-12-07T15:50:24.848413 (delta: 0.044975)         elapsed: 2.67935 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Install velero] **********************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/test.yml:34
2020-12-07T15:50:24.886453 (delta: 0.038007)         elapsed: 2.71739 ********* 
included: /experiments/zfs-localpv/functional/backup_and_restore/setup_dependency.yml for 127.0.0.1

TASK [Download velero binary] **************************************************
task path: /experiments/zfs-localpv/functional/backup_and_restore/setup_dependency.yml:1
2020-12-07T15:50:24.961326 (delta: 0.074841)         elapsed: 2.792263 ******** 
changed: [127.0.0. [...]

2020-12-07 16:19 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/incr_backup.yml
> +  shell: sleep 30
why do we have wait as first task in this file?

2020-12-07 16:19 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/backup.yml
> +  - include_tasks: "./incr_backup.yml"
add task name

2020-12-07 16:19 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/backup.yml
> +    shell: velero create schedule {{ schedule_name }} --schedule="*/1 * * * *" --snapshot-volumes --include-namespaces={{ app_ns }} --volume-snapshot-locations=incr --storage-location=default
can we make this schedule configurable

2020-12-07 16:19 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/incr_backup.yml
> +  shell: velero get backup | grep {{ schedule_name }} | tail -n1 | awk '{print $1}'
are we sure that the items are listed in ascending order?

2020-12-07 16:19 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/incr_restore.yml
> +
After restoring, can we verify the md5sum of files captured while backing up

2020-12-07 16:19 UTC, gprasath commented on experiments/zfs-localpv/functional/backup_and_restore/incr_backup.yml
> +  shell: sleep 180
Why do we need 3 minutes here?

2020-12-08 06:16 UTC, nsathyaseelan requested changes

2020-12-08 06:16 UTC, nsathyaseelan commented on experiments/zfs-localpv/functional/backup_and_restore/test.yml
> +          when: action == 'incr_restore'
@w3aman give the file name with meaning incremental_backup.  and for action also

2020-12-09 04:31 UTC, nsathyaseelan approved these changes
lgtm

2020-12-09 04:31 UTC, merged