feat[experiment]: litmusbook for velero based backup and restore on cstor volume
openebs/e2e-tests pull request #58
Opened 2019-11-06 00:20 UTC by shashank855

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>

**What this PR does / why we need it**:
- Adds litmusbook for performing velero based backup and restore on cstor volume.
- Includes setup-dependency.yml to install velero client inside litmus container,

**Following is the log of ansible test container:**
```
PLAYBOOK: test.yml *************************************************************
1 plays in ./apps/percona/functional/backup_and_restore/test.yml

PLAY [localhost] ***************************************************************
2019-11-06T00:11:02.861217 (delta: 0.04744)         elapsed: 0.04744 ********** 
=============================================================================== 

TASK [Gathering Facts] *********************************************************
task path: /apps/percona/functional/backup_and_restore/test.yml:1
2019-11-06T00:11:02.869387 (delta: 0.008145)         elapsed: 0.05561 ********* 
ok: [127.0.0.1]
META: ran handlers

TASK [include_tasks] ***********************************************************
task path: /apps/percona/functional/backup_and_restore/test.yml:12
2019-11-06T00:11:07.652674 (delta: 4.783259)         elapsed: 4.838897 ******** 
included: /utils/fcm/create_testname.yml for 127.0.0.1

TASK [Record test instance/run ID] *********************************************
task path: /utils/fcm/create_testname.yml:3
2019-11-06T00:11:07.702737 (delta: 0.050028)         elapsed: 4.88896 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Construct testname appended with runID] **********************************
task path: /utils/fcm/create_testname.yml:7
2019-11-06T00:11:07.744947 (delta: 0.042164)         elapsed: 4.93117 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] ***********************************************************
task path: /apps/percona/functional/backup_and_restore/test.yml:15
2019-11-06T00:11:07.783861 (delta: 0.038774)         elapsed: 4.970084 ******** 
included: /utils/fcm/update_litmus_result_resource.yml for 127.0.0.1

TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
task path: /utils/fcm/update_litmus_result_resource.yml:3
2019-11-06T00:11:07.847938 (delta: 0.064033)         elapsed: 5.034161 ******** 
changed: [127.0.0.1] => {"changed": true, "checksum": "cb23761ee0ecfea3a093f94c0443739c777b3007", "dest": "./litmus-result.yaml", "gid": 0, "group": "root", "md5sum": "0da5664e16958d4f3c263662ebe36b5c", "mode": "0644", "owner": "root", "size": 422, "src": "/root/.ansible/tmp/ansible-tmp-1572999067.89-18355546407617/source", "state": "file", "uid": 0}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:14
2019-11-06T00:11:08.380629 (delta: 0.532649)         elapsed: 5.566852 ******** 
changed: [127.0.0.1] => {"changed": true, "cmd": "cat litmus-result.yaml", "delta": "0:00:00.528147", "end": "2019-11-06 00:11:09.147837", "rc": 0, "start": "2019-11-06 00:11:08.619690", "stderr": "", "stderr_lines": [], "stdout": "---\napiVersion: litmus.io/v1alpha1\nkind: LitmusResult\nmetadata:\n\n  # name of the litmus testcase\n  name: velero-backup-restore \nspec:\n\n  # holds information on the testcase\n  testMetadata:\n    app:  \n    chaostype:  \n\n  # holds the state of testcase,  manually updated by json merge patch\n  # result is the useful value today, but anticipate phase use in future \n  testStatus: \n    phase: in-progress  \n    result: none ", "stdout_lines": ["---", "apiVersion: litmus.io/v1alpha1", "kind: LitmusResult", "metadata:", "", "  # name of the litmus testcase", "  name: velero-backup-restore ", "spec:", "", "  # holds information on the testcase", "  testMetadata:", "    app:  ", "    chaostype:  ", "", "  # holds the state of testcase,  manually updated by json merge patch", "  # result is the useful value today, but anticipate phase use in future ", "  testStatus: ", "    phase: in-progress  ", "    result: none "]}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:17
2019-11-06T00:11:09.183876 (delta: 0.803209)         elapsed: 6.370099 ******** 
changed: [127.0.0.1] => {"changed": true, "failed_when_result": false, "method": "patch", "result": {"apiVersion": "litmus.io/v1alpha1", "kind": "LitmusResult", "metadata": {"creationTimestamp": "2019-11-05T20:43:24Z", "generation": 31, "name": "velero-backup-restore", "resourceVersion": "73309", "selfLink": "/apis/litmus.io/v1alpha1/litmusresults/velero-backup-restore", "uid": "e93f55f9-000c-11ea-8939-42010a800092"}, "spec": {"testMetadata": {}, "testStatus": {"phase": "in-progress", "result": "none"}}}}

TASK [Generate the litmus result CR to reflect EOT (End of Test)] **************
task path: /utils/fcm/update_litmus_result_resource.yml:27
2019-11-06T00:11:09.976547 (delta: 0.792634)         elapsed: 7.16277 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Analyze the cr yaml] *****************************************************
task path: /utils/fcm/update_litmus_result_resource.yml:38
2019-11-06T00:11:10.011129 (delta: 0.034541)         elapsed: 7.197352 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Apply the litmus result CR] **********************************************
task path: /utils/fcm/update_litmus_result_resource.yml:41
2019-11-06T00:11:10.047135 (delta: 0.035964)         elapsed: 7.233358 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Verify that the AUT is running] ******************************************
task path: /apps/percona/functional/backup_and_restore/test.yml:19
2019-11-06T00:11:10.081579 (delta: 0.034402)         elapsed: 7.267802 ******** 
included: /utils/k8s/check_deployment_status.yml for 127.0.0.1

TASK [Check the pod status] ****************************************************
task path: /utils/k8s/check_deployment_status.yml:8
2019-11-06T00:11:10.138188 (delta: 0.056572)         elapsed: 7.324411 ******** 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "cmd": "kubectl get pods -n app-percona-ns -l name=percona --no-headers -o custom-columns=:status.phase", "delta": "0:00:01.035839", "end": "2019-11-06 00:11:11.312674", "rc": 0, "start": "2019-11-06 00:11:10.276835", "stderr": "", "stderr_lines": [], "stdout": "Running", "stdout_lines": ["Running"]}

TASK [obtain the number of replicas.] ******************************************
task path: /utils/k8s/check_deployment_status.yml:22
2019-11-06T00:11:11.361330 (delta: 1.223105)         elapsed: 8.547553 ******** 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [Obtain the ready replica count and compare with the replica count.] ******
task path: /utils/k8s/check_deployment_status.yml:29
2019-11-06T00:11:11.400357 (delta: 0.038984)         elapsed: 8.58658 ********* 
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_tasks] ***********************************************************
task path: /apps/percona/functional/backup_and_restore/test.yml:22
2019-11-06T00:11:11.440558 (delta: 0.040157)         elapsed: 8.626781 ******** 
included: /apps/percona/functional/backup_and_restore/setup_dependency.yml for 127.0.0.1

TASK [Downloading velero binary] ***********************************************
task path: /apps/percona/functional/backup_and_restore/setup_dependency.yml:1
2019-11-06T00:11:11.508113 (delta: 0.06751)         elapsed: 8.694336 ********* 
changed: [127.0.0.1] => {"attempts": 1, "changed": true, "checksum_dest": null, "checksum_src": "24c98ca1c9cfe5c754c76c07ba6cbc517bc68f92", "dest": "./velero-v1.1.0-linu [...]

2019-11-06 05:02 UTC, mynktl requested changes
Changes are good. I have given few comments about passing value through argument instead of defining it in core function.
Is this test is meant for Percona only? If someone wants to write backup/restore test for other application?

2019-11-06 05:02 UTC, mynktl commented on apps/percona/functional/backup_and_restore/setup_dependency.yml
> +    url: "https://github.com/vmware-tanzu/velero/releases/download/v1.1.0/velero-v1.1.0-linux-amd64.tar.gz"
Let's define an environment variable for velero version `v1.1.0` and also for velero-plugin so we don't need to modify core files in future for version change.

2019-11-06 05:02 UTC, mynktl commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +       velero backup create percona-backup --include-namespaces={{ app_ns }} --snapshot-volumes --volume-snapshot-locations=minio
Can we generate unique backup name here, instead of using static name? And can we pass this as an argument?

2019-11-06 05:02 UTC, mynktl commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +     failed_when: "'created' not in volume_snapshot_location.stdout"
This is part of velero setup. Please move this to `setup_dependency.yml`.

2019-11-06 05:02 UTC, mynktl commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +       velero backup create percona-backup --include-namespaces={{ app_ns }} --snapshot-volumes --volume-snapshot-locations=minio
Also volumeSnapshotLocation.

2019-11-06 05:42 UTC, gprasath commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +     retries: 15
is this sufficient for backing up

2019-11-06 05:42 UTC, gprasath commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +   - name: Restoreing application
restoring

2019-11-06 05:42 UTC, gprasath commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +       velero backup create percona-backup --include-namespaces={{ app_ns }} --snapshot-volumes --volume-snapshot-locations=minio
backup name can be user defined. Use variable

2019-11-06 05:42 UTC, gprasath commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +       velero backup create percona-backup --include-namespaces={{ app_ns }} --snapshot-volumes --volume-snapshot-locations=minio
snapshot location as well

2019-11-06 05:42 UTC, gprasath commented on apps/percona/functional/backup_and_restore/backup-restore.yml
> +     shell: velero get restore | grep percona-backup | awk '{print $1}'
we can pass the backup name here

2019-11-06 05:56 UTC, gprasath commented on apps/percona/functional/backup_and_restore/setup_dependency.yml
> +  shell: velero plugin add openebs/velero-plugin:ci
lets not hardcode the version

2019-11-07 13:14 UTC, gprasath commented on apps/percona/functional/backup_and_restore/setup_dependency.yml
> +  failed_when: "'v1.1.0' not in velero_version.stdout"
version not to be hardcoded as we are ow getting it through env

2019-11-08 05:50 UTC, gprasath approved these changes

2019-11-08 05:50 UTC, merged